print(f"df columns: {len(df.columns)}")
print(f"df_y columns: {len(df_y.columns)}")
print(f"Overlapping: {len(df.columns.intersection(df_y.columns))}")
print(f"Only in df: {len(df.columns.difference(df_y.columns))}")
print(f"Only in df_y: {len(df_y.columns.difference(df.columns))}")